server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: item-service # 应用名称
  devtools:
    restart:
      enabled: false
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true
eureka:

  client:

    service-url:

      defaultZone: http://127.0.0.1:10086/eureka

  instance:

    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳

    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

    prefer-ip-address: true

    ip-address: 127.0.0.1

    instance-id: ${spring.application.name}:${server.port}
logging:
    level:
        com.leyou.item.mapper: DEBUG